name: Check & lint Python code

on:
  push:

jobs:
  check-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Black
        uses: psf/black@stable
        with:
          src: "./src"
      - name: Pyright
        uses: jakebailey/pyright-action@v1
