name: Check & lint Python code

on:
  push:

jobs:
  check-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Black
        uses: microsoft/action-python@0.7.1
        with:
          black: true
      - name: Pyright
        uses: jakebailey/pyright-action@v1
